---
- name: Test Calendar module
  hosts: localhost
  gather_facts: yes
  
  pre_tasks:
    # Z is the zone designator for the zero UTC offset. 
    - name: Print the time (ISO 8601) - Module input
      debug:
        var: ansible_date_time.iso8601

  roles:
    - role: go-role

  # tasks:
  #   - name: Test the module
  #     calendar:
  #       name: Testing the Calendar module
  #       time: "{{ ansible_date_time.iso8601 }}"
  #       run_once: true
  #     register: output

  post_tasks:
    - name: Print out Calendar module output
      debug:
        var: output